### ISSUE TITLE
TODO for first Release

### ISSUE THREAD

**Issue by flxkrmr** [flxkrmr/eec-iv-reader-gui#1]
- [x] Readme/Manual
- [x] Disconnect Button
- [x] Test/Configure Installer
- [x] Electron Updater and Github releases
- [ ] Board Updater
- [x] Live Data only the ones that are correct
